INSERT INTO TB_COLABORADOR (NOME_COLABORADOR) VALUES ('CAROLINE');
INSERT INTO TB_COLABORADOR (NOME_COLABORADOR) VALUES ('TIAGO');
INSERT INTO TB_COLABORADOR (NOME_COLABORADOR) VALUES ('CARLOS');
INSERT INTO TB_COLABORADOR (NOME_COLABORADOR) VALUES ('FERNANDO');
INSERT INTO TB_COLABORADOR (NOME_COLABORADOR) VALUES ('FABRICIO');
INSERT INTO TB_COLABORADOR (NOME_COLABORADOR) VALUES ('NILTON');


INSERT INTO TB_TAREFA (DATA_HORA_FIM,DATA_HORA_INICIO,DESCR_TAREFA,PRIORIDADE_TAREFA ,STATUS_TAREFA,COLABORADOR_ID_COLABORADOR) 
VALUES ('2020-07-13T20:50:07','2020-07-13T20:50:07','ESTUDAR','ALTA','PENDENTE',1);
INSERT INTO TB_TAREFA (DATA_HORA_FIM,DATA_HORA_INICIO,DESCR_TAREFA,PRIORIDADE_TAREFA ,STATUS_TAREFA,COLABORADOR_ID_COLABORADOR) 
VALUES ('2020-07-13T20:50:07','2020-07-13T20:50:07','ESTUDAR','ALTA','CONCLUIDO',2);
INSERT INTO TB_TAREFA (DATA_HORA_FIM,DATA_HORA_INICIO,DESCR_TAREFA,PRIORIDADE_TAREFA ,STATUS_TAREFA,COLABORADOR_ID_COLABORADOR) 
VALUES ('2020-07-13T20:50:07','2020-07-13T20:50:07','ESTUDAR','ALTA','PENDENTE',3);
INSERT INTO TB_TAREFA (DATA_HORA_FIM,DATA_HORA_INICIO,DESCR_TAREFA,PRIORIDADE_TAREFA ,STATUS_TAREFA,COLABORADOR_ID_COLABORADOR) 
VALUES ('2020-07-13T20:50:07','2020-07-13T20:50:07','ESTUDAR','ALTA','EM ANDAMENTO',4);