INSERT INTO TB_COLABORADOR (NOME_COLABORADOR) VALUES ('CAROLINE');
INSERT INTO TB_COLABORADOR (NOME_COLABORADOR) VALUES ('TIAGO');
INSERT INTO TB_COLABORADOR (NOME_COLABORADOR) VALUES ('CARLOS');
INSERT INTO TB_COLABORADOR (NOME_COLABORADOR) VALUES ('FERNANDO');
INSERT INTO TB_COLABORADOR (NOME_COLABORADOR) VALUES ('FABRICIO');
INSERT INTO TB_COLABORADOR (NOME_COLABORADOR) VALUES ('NILTON');